[package]
name = "symscan-airr"
authors = ["Yuta Nagano"]
version = "0.1.0"
edition = "2021"
description = "Fast similarity measurement between adaptive immune receptor repertoire data, powered by symscan."
repository = "https://github.com/yutanagano/symscan"
homepage = "https://github.com/yutanagano/symscan"

[dependencies]
clap.workspace = true
csv = "1.4.0"
foldhash.workspace = true
hashbrown.workspace = true
itertools.workspace = true
rayon.workspace = true
symscan.workspace = true
thiserror.workspace = true
