[package]
name = "symscan-cli"
authors = ["Yuta Nagano"]
version = "0.8.3"
edition = "2021"
description = "Fast discovery of similar strings in bulk"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yutanagano/symscan"
homepage = "https://github.com/yutanagano/symscan"

[dependencies]
clap.workspace = true
symscan.workspace = true
rayon.workspace = true

[[bin]]
name = "symscan"
path = "src/main.rs"
