[package]
name = "symscan-py"
authors = ["Yuta Nagano"]
version.workspace = true
edition = "2021"
description = "Python bindings for symscan"
repository = "https://github.com/yutanagano/symscan"
homepage = "https://github.com/yutanagano/symscan"

[dependencies]
symscan = { version = "0.8", path = "../symscan/" }
pyo3 = { version = "0.29", features = ["abi3-py310"] }
numpy = "0.29"

[lib]
crate-type = ["cdylib"]
